### ISSUE TITLE
Conda.jl use an already installed version of mini/ana-conda

### ISSUE THREAD

**Issue by hayd** [Luthaf/Conda.jl#12]
I already have conda as my default python, will Conda.jl find this? If not, could it?

Either way it would be great to mention this in the documentation/README.

Perhaps also useful would be the example of how to install ipython/pycall.

**Comment by Luthaf** [comment]
Conda.jl will not find it, and I do not think it should. This package is not made for an alternative Python installation, but rather to be used by other julia packages as a dependency provider. It happens to use `conda` internally, but this is only an implementation detail. 

> Either way it would be great to mention this in the documentation/README.

You are right!

> Perhaps also useful would be the example of how to install ipython/pycall.

Why not. PyCall can not be installed with Conda.jl, but iPython can, and IJulia will use it. See JuliaLang/IJulia.jl#357

**Comment by hayd** [comment]
Thanks, that would be great!

>  This package is not made for an alternative Python installation, but rather to be used by other julia packages as a dependency provider.

One thing I've found frustrating in the past is having multiple python/conda installations kicking around. If I pip/conda install something, I might be confused if it's unavailable from julia... Although this would also be the case if Conda.jl used an environment in my `~/.miniconda` install.... So maybe I haven't quite yet understood how this fits...

**Comment by stevengj** [comment]
PyCall can now be installed with Conda.jl, and also PyPlot.

**Comment by Luthaf** [comment]
> PyCall can now be installed with Conda.jl, and also PyPlot.

What I meant is that you will never run `Conda.add("PyPlot")`, but uses `Pkg.add("PyPlot")`. Then, internally, PyPlot can (and do now) uses Conda to get its own dependencies.

**Comment by Luthaf** [comment]
Closing this, feel free to reopen if you still have questions.

**Comment by hayd** [comment]
I don't think this is mentioned in the README (yet).

Specifically IIUC suppose I already have a miniconda installation (say at ~/anaconda), Conda.jl downloads another version of miniconda and install ipython/whatever into a single conda environment (the default)?

The original issue was whether this could happen as a special conda environment in ~/anaconda.

**Comment by Luthaf** [comment]
> I don't think this is mentioned in the README (yet).

Yes, I forgot this part.

For conda environments, also see #19.

**Comment by hayd** [comment]
It's still unclear why using system conda if available (using a "_jlconda" or similarly named environment to install/use), would be a bad idea. Note: this is different from the system *python*, I'm not suggesting that.

I can see how it is easier that Conda.jl has complete ownership over it's own miniconda installation but it seems to me like there is a lot of unnecessary duplication in doing so.

**Comment by stevengj** [comment]
Having our own private miniconda installation gives us much more reliable installation of dependencies.   If we use the user's conda installation, they could have mucked it up in almost any conceivable way.  This is the whole point of Conda.

If you want to use your own Anaconda installation, the right place to do it is in the packages that *use* Conda.   For example, IJulia, PyCall (and PyPlot, and SymPy) only use Conda if they don't find a working `jupyter` or `python` executable already installed, and both allow you choose a specific `jupyter` or `python` on your system via environment variables.   If you do that, then the Conda package may never install miniconda at all (unless `Conda.add` is called by some other package).

**Comment by hayd** [comment]
> user's conda installation, they could have mucked it up in almost any conceivable way.

I thought the whole point of using/creating an environment is they can't.

**Comment by stevengj** [comment]
If the separate conda environment uses its own Python and its own set of packages, then there's not much advantage over just doing a private miniconda installation.  Any shared resource could be mucked up by the user.  Even their `conda` program itself might be out of date.

**Comment by stevengj** [comment]
(Never underestimate the ability of users to creatively muck up their system. :wink:)

**Comment by Luthaf** [comment]
>  Even their conda program itself might be out of date.

The conda program automatically update itself at every package installation.

> I thought the whole point of using/creating an environment is they can't.

I do not think we can lock an environment using Conda, and I do no know what happen if `__jlconda` uses `libfoo==4.3.5` and the root environment uses `libfoo==6.9.3`.

**Comment by hayd** [comment]
You can't lock it, but nor can you stop a user from mucking about with the current miniconda installed by Conda.jl.

> I do no know what happen if __jlconda uses libfoo==4.3.5 and the root environment uses libfoo==6.9.3.

That's what [conda environments](http://conda.pydata.org/docs/using/envs.html) are for!

**Comment by davidanthoff** [comment]
I very strongly concur with @stevengj on this: this package should leave any existing conda install entirely alone and just operate on the private miniconda install. I have a different reason, though: there are a whole bunch of packages using this now that on the face of it have no relation to Python whatsoever (e.g. my ExcelReaders package). As a user I would be VERY annoyed if a ``Pkg.add("ExcelReaders")`` messed around with my existing conda setup in any way, depended on that or anything else. Much cleaner if this is kept completely separate.

**Comment by hayd** [comment]
I think that there may be some misunderstanding about conda environments, nevertheless the consensus seems to be not to do this.

**Comment by davidanthoff** [comment]
As a user, I wouldn't want ``Pkg.add("ExcelReaders")`` to add an environment to conda. This is just weird for users: something about Excel files adds something to their conda environment list, why? Plus, conda environments have the notion of an active environment, and again, I wouldn't want some random julia pacakge to change what is the current active environment.

**Comment by Luthaf** [comment]
This could be nice to have **as an opt-in behaviour** (the default being using the private local conda installation), but I do not see much use cases for it. The only one I can think of is for users with a quota on the number of files/the size of there `/home` directory, and with a pre-existing conda installation. Any other uses cases worth the work of making this work *together with the current implementation*?
