### ISSUE TITLE
Conda gets confused by CONDA environment variables

### ISSUE THREAD

**Issue by stevengj** [Luthaf/Conda.jl#13]
I have been playing with Conda on my machine, where I also have Anaconda installed globally.    My understanding is that the global Anaconda should not interact with Conda, which is intended to be a "private" Julia miniconda installation.

However, if I've activated Python 3 in my global Anaconda environment, it sets environment variables `CONDA_ENV_PATH=/Users/stevenj/anaconda/envs/py3` and `CONDA_DEFAULT_ENV=py3`.  These seem to interact badly with Conda.jl, e.g. I get
```
julia> Conda.add("jupyter")
Fetching package metadata: ....
Error: environment does not exist: /Users/stevenj/.julia/v0.5/Conda/deps/usr/envs/py3
#
# Use 'conda create' to create an environment before installing packages
# into it.
#
ERROR: failed process: Process(`/Users/stevenj/.julia/v0.5/Conda/deps/usr/bin/conda install -y jupyter`, ProcessExited(1)) [1]
 in run at ./process.jl:531
 in add at /Users/stevenj/.julia/v0.5/Conda/src/Conda.jl:114
```

Suggestion: run the `conda` program in a "sanitized" environment.  e.g. just use
```jl
setenv(`conda ....`, ASCIIString[])
```
to create a version of a `conda` command with all environment variables removed.

**Comment by Luthaf** [comment]
> My understanding is that the global Anaconda should not interact with Conda, which is intended to be a "private" Julia miniconda installation.

That is also my idea. I'll try to do this!

**Comment by Luthaf** [comment]
I had to selectively remove the variables starting by `CONDA` from the environment, as conda rely on PATH being set, and maybe others.

Will merge 4e9f300 when the tests passes.

**Comment by stevengj** [comment]
Thanks!
