### ISSUE TITLE
Add a .condarc file to manage channels

### ISSUE THREAD

**Issue by Luthaf** [Luthaf/Conda.jl#20]
This will make new channels survive new julia sessions.

See http://conda.pydata.org/docs/config.html?highlight=condarc#the-conda-configuration-file-condarc for the documentation about condarc.

**Comment by jakirkham** [comment]
:+1:

**Comment by jakirkham** [comment]
Neat. Now one can do cool things like add [conda-forge]( http://conda-forge.github.io/ ).

**Comment by Luthaf** [comment]
Yeah, that conda-forge article remind me of this issue, and gave me the hint to the `conda config` command.

**Comment by jakirkham** [comment]
> Yeah, that conda-forge article remind me of this issue...

Which one? 😄

Also, if there are any packages that you are interested in getting in, we would be more than happy to guide you through the process.

**Comment by Luthaf** [comment]
This one: https://www.continuum.io/blog/developer-blog/community-conda-forge. Sorry, I did not follow your link, and assumed you gave the same link I read yesterday =)

I might try to get my [three packages](https://github.com/chemfiles/conda-recipes) in conda-forge someday. What are you using for Linux builds ? I got some issues when building them with a too recent glibc.

**Comment by jakirkham** [comment]
> This one: https://www.continuum.io/blog/developer-blog/community-conda-forge. Sorry, I did not follow your link, and assumed you gave the same link I read yesterday 😄

Ah ok. What did you think?

There was this [one]( http://wesmckinney.com/blog/conda-forge-centos-moment/ ) that someone else did as a commentary on conda-forge. So, I didn't know if you meant that one. Who knows maybe others have written articles too.

> I might try to get my three packages in conda-forge someday.

That sounds great! Honestly, I think you will find this is quite simple.

> What are you using for Linux builds ?

We use this [docker image]( https://hub.docker.com/r/condaforge/linux-anvil/ ), which is built from this [source]( https://github.com/conda-forge/docker-images/tree/master/linux-anvil ).

> I got some issues when building them with a too recent glibc.

Absolutely. This is something we take very seriously. Currently, we build on CentOS 6, which has a glibc of 2.12. This seems to be old enough in practice so far. Is that old enough for you?

There has been some discussion about switching to CentOS 5 before, but there are some issues like it's [EOL is next year]( https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d ), NVIDA CUDA 7.5 [doesn't support]( http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#system-requirements ) it, plus there have been some [build troubles]( https://github.com/conda-forge/conda-forge.github.io/issues/63#issuecomment-205839048 ).

**Comment by Luthaf** [comment]
CentOS 6 should do it for me, except that I need a C++11 compiler. So maybe something using

**Comment by jakirkham** [comment]
> CentOS 6 should do it for me, except that I need a C++11 compiler. So I should maybe use another compiler with C++11 support, and statically linking to libstdc++.

Not a problem. On Linux we provide devtoolset-2, which includes `gcc` 4.8.2. This has C++11 support. It also does partial static linking with some of `libgcc` so that the end user only needs to have CentOS 6 or newer (just links to standard system libraries).

> I'll look to put my formulas in conda-forge for the next release!

Awesome! 👍 Looking forward to working with you, @Luthaf.
