### ISSUE TITLE
Install non-conda packages

### ISSUE THREAD

**Issue by codles** [Luthaf/Conda.jl#30]
Is there a way to install non conda packages?

On OSX I would usually run  `pip2 install -e 'git+https://github.com/mne-tools/mne-python#egg=mne-dev'`. But I would like to use your package to standardise across operating systems.

I have installed the requirements using
```julia
Conda.add("NumPy")
Conda.add("SciPy")
Conda.add("matplotlib")
```
But the following line fails
```julia
Conda.add("git+https://github.com/mne-tools/mne-python#egg=mne-dev")
```

Thanks

**Comment by Luthaf** [comment]
You need to call pip to do that. So what should work is 

```julia
Conda.add("pip")
pip = joinpath(Condat.BINDIR, "pip")
run(`pip install -e git+https://github.com/mne-tools/mne-python#egg=mne-dev`)
```

On windows is might be 
```julia
pip = joinpath(Condat.SCRIPTDIR, "pip")
# On UNIX, Condat.SCRIPTDIR == Condat.BINDIR
```

**Comment by codles** [comment]
Thanks, The commands ran successfully.

Unfortunetly it has installed to my local python installation . The final output to the `run(pip...)` command is 

```bash
 Installing mne script to C:\Python27\Scripts
 Installed c:\users\rluke\appdata\local\julia-0.4.3\src\mne
```
Running `@pyimport mne as mne` fails in julia. But running `import mne as mne` in my local python install works.

Is this a problem of having python already on my system? Or is it part of the egg install system (I dont use python much)?

**Comment by Luthaf** [comment]
There was a typo in my first comment (and thus in the email notification). Did you actually ran `run($pip ...)` or `run(pip ...)`? The missing `$` character was my typo.

**Comment by codles** [comment]
Fantastic! Worked a treat. Great package. Thanks for the support.

**Comment by Sinansi** [comment]
I am trying to install a library that can only be installed using pip command.
I got an error saying "ERROR: UndefVarError: pip not defined".
I thought it is bug until I saw Luthaf comment.

@oxinabox  Could you please mention on the library home page that we need to add pip before using it?

**Comment by Sinansi** [comment]
I installed pip and it appears under Conda.list(), but the problem still persist.

julia> Conda.pip("install", "ta")
ERROR: UndefVarError: pip not defined
