### ISSUE TITLE
Support in ScikitLearn.jl

### ISSUE THREAD

**Issue by cstjean** [Luthaf/Conda.jl#32]
Hey, thanks for the heads up regarding the latest update. ScikitLearn.jl no longer requires the Python library, though it's a (very useful) optional dependency. Can I tell my users to enter `import Conda; Conda.add("scikit-learn")` and it will Just Work?

**Comment by Luthaf** [comment]
I don't know about scikit-learn, so I can only try to guess. If it is a Python library, it should Just Work™ given

1. You have Conda in your REQUIRE file (easy)
2. You have a way to reach the python library from Julia. That may need PyCall, and making sure PyCall is using Conda's provided Python (harder)

**Comment by cstjean** [comment]
> That may need PyCall, and making sure PyCall is using Conda's provided Python (harder)

So far my README has been saying "install conda", then "conda install scikit-learn" and AFAIK that works, PyCall is able to import it. Is there an additional difficulty with `Conda.jl`? What happens if full-conda was already installed, does Conda.jl's miniconda just add another `PATH` for Python to find libraries?

**Comment by Luthaf** [comment]
I do not know how PyCall search for Python library, but it looked like PyCall worked with only one Python installation, either the system one or a conda one. Maybe @stevengj can help us here. But if PyCall uses the system Python, I do not see how it could find the conda installed packages.

> What happens if full-conda was already installed, does Conda.jl's miniconda just add another PATH for Python to find libraries?

No, Conda.jl always uses it's own miniconda installation. This make it easier to work with and guarantee a coherent state.

**Comment by stevengj** [comment]
PyCall can use *either* the Conda Python, or some other Python installation (e.g. a system-wide Anaconda distro installation), but not both simultaneously.

I would do something similar to how PyPlot checks for matplotlib: install it via Conda if possible, or suggest that the user reconfigure PyCall to use Conda: https://github.com/stevengj/PyPlot.jl/blob/2dcaebfd4e207367dedd88712ec06ddd270e4573/src/PyPlot.jl#L239-L256

I should probably just add a function to PyCall like `PyCall.pyrequire(module, condapkg)` that does this, since several packages seem to use this kind of functionality.

**Comment by Luthaf** [comment]
> I should probably just add a function to PyCall like PyCall.pyrequire(module, condapkg) that does this, since several packages seem to use this kind of functionality.

Python version aside, it should be as easy as adding an entry to `sys.path` to be able to import packages from both the system installation, and a Conda.jl provided installation.

**Comment by cstjean** [comment]
@stevengj Thanks for that code snippet, I'll try it out.

**Comment by stevengj** [comment]
With PyCall 1.5 (shortly to be tagged), you can now do `pyimport_conda("sklearn", "scikit-learn")` and it will import `sklearn`, auto-installing with Conda if PyCall is configured to use Conda, and printing an error message explaining how to switch to Conda if not.

**Comment by cstjean** [comment]
👍

**Comment by Luthaf** [comment]
@cstjean does that fix the issue for you?

**Comment by cstjean** [comment]
Well, it's rather hard to test these things, but presumably yes. I haven't checked if it works on travis yet, I assume that I can now remove

```
before_install:
    #install scikit-learn to test functionallity
  - julia -e 'Pkg.add("Conda")'
  - julia -e 'using Conda; Conda.add("scikit-learn")'
```

and rely on Steven's new function to install it automatically. I'll reopen if I get a problem. Thanks for your help!
