### ISSUE TITLE
add(package, channel)?

### ISSUE THREAD

**Issue by stevengj** [Luthaf/Conda.jl#33]
It seems like it would be nice to be able to do `Conda.add(package, channel)` in order to run `conda install -c channel package`.

In particular, suppose that I only want to use a channel to install a particular package.  In that case, do I really want to do `Conda.add_channel(channel)` to add the channel globally?

This came up in crbinz/SGP4.jl#5

**Comment by stevengj** [comment]
Similarly for PyX.jl (cc @bnewbold), since that uses the `bioconda` channel.

**Comment by Luthaf** [comment]
> In particular, suppose that I only want to use a channel to install a particular package. In that case, do I really want to do Conda.add_channel(channel) to add the channel globally?

Yes, because if you do not add them globally, some future operations like `update` or `rm` will fail. And there should not be silent overriding of packages by adding a new channel. So I think it is really better to just add the channel directly.

**Comment by stevengj** [comment]
Ah, okay... if `conda install -c channel package` does not "remember" the channel for future updates, that makes it a lot less useful.
