### ISSUE TITLE
Error: Could not find anaconda.org user foo

### ISSUE THREAD

**Issue by tkelman** [Luthaf/Conda.jl#34]
Most packages that rely on Conda.jl seem to have started failing within the last 2 days: http://pkg.julialang.org/pulse.html

**Comment by Luthaf** [comment]
This looks like a change in conda's handling of the `defaults` set of channels, leaving the code in incoherent state after the tests. 8ceedda4e8879fb0fa3e673227b934baff27c388 should fix it, at least for Conda.jl. Do you have a test log for another failing package ?

**Comment by tkelman** [comment]
http://pkg.julialang.org/logs/ExcelReaders_0.4.log ?

**Comment by Luthaf** [comment]
Ok, so it looks like the errors occurs chen installing PyCall. Is there any cleanup between the tests on julia pulse ? It looks like some previous files from Conda tests are still around.

**Comment by tkelman** [comment]
Some subset of the tests run in the same VM. It's alphabetical at the moment so A-L on the nightly PkgEval runs will happen in the same run. Since you are trying to clean up after yourself I guess it's just an unintended consequence. I'll probably rewrite PkgEval to be docker-based and have more isolation for Linux runs at some point, but good to know the problem isn't actually as widespread as it looks.

**Comment by Luthaf** [comment]
Yep, I'll tag a new version and we'll see if all this is fixed.

**Comment by tkelman** [comment]
If you could tag soon, would make PkgEval greener. Thanks!

**Comment by Luthaf** [comment]
I was waiting for Appveyor to go green, now it is done!

**Comment by tkelman** [comment]
This may have been also fixed upstream, last night's PkgEval ran fine and started before we merged the 0.2.1 tag. Good enough!
