### ISSUE TITLE
Requires julia 0.3.3 due to usage of chmod

### ISSUE THREAD

**Issue by martinholters** [Luthaf/Conda.jl#35]
`chmod` has only been added to Base in 0.3.3, but [is used here](https://github.com/Luthaf/Conda.jl/blob/master/src/Conda.jl#L126), so requiring `julia 0.3` is not enough. Note that a proper fix will involve updating metadata `requires`'s of past versions.

**Comment by Luthaf** [comment]
> Note that a proper fix will involve updating metadata requires's of past versions.

Is this even possible? @tkelman, since you seems to be the one in charge of METADATA.jl, what do you think ?

**Comment by tkelman** [comment]
yes, you can open a pr modifying the contents of past tag's requires files. also there are octal literals `0o755` that you may find convenient there.

**Comment by martinholters** [comment]
Thanks for fixing.
