### ISSUE TITLE
Error in travis

### ISSUE THREAD

**Issue by tbreloff** [Luthaf/Conda.jl#37]
```
INFO: Installing matplotlib via the Conda matplotlib package...
Fetching package metadata ...Error: Invalid index file: https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2: couldn't find end of stream
```

Any ideas?  Subsequent errors imply that matplotlib was never installed.

**Comment by Luthaf** [comment]
This looks like an error from the [conda](https://github.com/conda/conda) infrastructure side. 

I can download this file now, what happen if you restart the Travis build ?

**Comment by tbreloff** [comment]
Thanks... running again.  I'll let you know.

**Comment by tbreloff** [comment]
Build passed... guess it was just a freak error.  Thanks and sorry for the noise.
