### ISSUE TITLE
Please tag a version

### ISSUE THREAD

**Issue by davidanthoff** [Luthaf/Conda.jl#39]
The latest tagged version has deprecation warnings on julia 0.5, master doesn't. Would be nice to clean up packages as quickly as possible for the julia 0.5 release.

**Comment by Luthaf** [comment]
Done ! https://github.com/JuliaLang/METADATA.jl/pull/5816

When is the 0.5 release planned btw?

**Comment by davidanthoff** [comment]
God knows. They released a release candidate that has known bugs and is not a candidate for a release a week ago. I quite frankly don't understand the core's way of managing releases, but I have a *very* hard time imagining that one can say anything useful about release dates with the current project management style they have...
