### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by svaksha** [Luthaf/Conda.jl#4]
Hi, 
On Ubuntu-14.04-LTS, running Julia-0.4 (git master) I get the following errors while trying to install Conda.jl :

```
INFO: Building Conda
INFO: Downloading miniconda installer …
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
==========================================================================[ ERROR: Conda ]==========================================================================

LoadError: LoadError: InitError: failed process: Process(`curl -o /home/sva/.julia/v0.4/Conda/deps/usr/installer -L https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh`, ProcessExited(77)) [77]
during initialization of module Conda
while loading /home/sva/.julia/v0.4/Conda/src/Conda.jl, in expression starting on line 349
while loading /home/sva/.julia/v0.4/Conda/deps/build.jl, in expression starting on line 1

====================================================================================================================================================================

==========================================================================[ BUILD ERRORS ]==========================================================================

WARNING: Conda had build errors.

 - packages with build errors remain installed in /home/sva/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Conda")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================================================================================

julia> Pkg.build("Conda")
INFO: Building Conda
==========================================================================[ ERROR: Conda ]==========================================================================

LoadError: could not spawn `/home/sva/.julia/v0.4/Conda/deps/usr/bin/conda list --json`: no such file or directory (ENOENT)
while loading /home/sva/.julia/v0.4/Conda/deps/build.jl, in expression starting on line 2

====================================================================================================================================================================

==========================================================================[ BUILD ERRORS ]==========================================================================

WARNING: Conda had build errors.

 - packages with build errors remain installed in /home/sva/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Conda")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================================================================================

julia> 
```
Thanks!

**Comment by Luthaf** [comment]
There are two errors here: one from curl

```
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

And one from Conda:
```
LoadError: could not spawn `/home/sva/.julia/v0.4/Conda/deps/usr/bin/conda list --json`: no such file or directory (ENOENT)
while loading /home/sva/.julia/v0.4/Conda/deps/build.jl, in expression starting on line 2
```

The second one should be fixed in the `fix-4` branch, but I do not see what to do for the first one. Could you please try to do the following to test the fix?

```
julia> Pkg.checkout("Conda", "fix-4")
julia> Pkg.build("Conda")
julia> Pkg.test("Conda")
julia> Pkg.free("Conda")
```

**Comment by svaksha** [comment]
# 1. Curl error
Tried it again, no luck.

julia> using Conda
INFO: Recompiling stale cache file /home/sva/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Recompiling stale cache file /home/sva/.julia/lib/v0.4/URIParser.ji for module URIParser.
INFO: Recompiling stale cache file /home/sva/.julia/lib/v0.4/SHA.ji for module SHA.
INFO: Downloading miniconda installer …
curl: (6) Couldn't resolve host 'repo.continuum.io'
ERROR: LoadError: InitError: failed process: Process(`curl -o /home/sva/.julia/v0.4/Conda/deps/usr/installer -L https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh`, ProcessExited(6)) [6]


# 2. Fix-4 error
julia> Pkg.checkout("Conda", "fix-4")
INFO: Checking out Conda fix-4...
fatal: Cannot update paths and switch to branch 'fix-4' at the same time.
Did you intend to checkout 'origin/fix-4' which can not be resolved as commit?
ERROR: failed process: Process(`git --work-tree=/home/sva/.julia/v0.4/Conda --git-dir=/home/sva/.julia/v0.4/Conda/.git checkout -q -B fix-4 -t origin/fix-4`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:548
 in run at process.jl:524
 in anonymous at pkg/entry.jl:192
 in __transact#393__ at pkg/git.jl:97
 in _checkout at pkg/entry.jl:190
 in checkout at pkg/entry.jl:205
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31

**Comment by Luthaf** [comment]
>  curl: (6) Couldn't resolve host 'repo.continuum.io'

That is the main issue ... Can you access this URL with your web browser?

> Fix-4 error

I just realise that Conda was not tested on Linux with Travis. I am activating this, and will try to get it work first.

**Comment by svaksha** [comment]
Yes, I can access the URL on the web (would it help if there was an extra space between the tick at the end of the URL?). 
Ok, please announce that (tested on Linux with Travis) somewhere so that I can update later.
Thanks.

**Comment by Luthaf** [comment]
> Yes, I can access the URL on the web (would it help if there was an extra space between the tick at the end of the URL?). 

I'll try to use the http URL instead of the https here. It may help for people behind a firewall.

**Comment by Luthaf** [comment]
The Linux build is green! https://travis-ci.org/Luthaf/Conda.jl/builds/78566555

Can you try again with either `Pkg.checkout("Conda", "fix-4")` of `Pkg.checkout("Conda", "origin/fix-4")` ? And if any of them work, can you do the following?

```
julia> cd(Pkg.dir("Conda"))
julia> run(`git fetch origin`)
julia> run(`git checkout fix-4`)
```

**Comment by svaksha** [comment]
Thanks, it gave similar errors but when I tried it 2-3 times it didnt throw errors, so I assume it works:

```
julia> run(`git checkout fix-4`)
Already on 'fix-4'
Your branch is up-to-date with 'origin/fix-4'.

julia> using Conda

julia> Pkg.update()
INFO: Updating METADATA...
```



INFO: Updating Conda...
INFO: Updating DataStructures...
INFO: Computing changes...
INFO: No packages to install, update or remove
```
Thanks.

**Comment by Luthaf** [comment]
Merged in master ! Within a few days you should be able to run `Pkg.free("Conda")` and use the official release.

**Comment by Luthaf** [comment]
A new version have been tagged, you can now run 

```
Pkg.free("Conda")
Pkg.update()
```

To get it.

**Comment by svaksha** [comment]
On Mon, Sep 7, 2015 at 3:14 PM, Luthaf <notifications@github.com> wrote:

> Pkg.free("Conda")


​Thanks @luthaf

SVAKSHA ॥  http://about.me/svaksha  ॥
