### ISSUE TITLE
Issues installing Conda

### ISSUE THREAD

**Issue by dhoegh** [Luthaf/Conda.jl#5]
I get some error when trying to install ``Conda`
```
julia> Pkg.add("Conda")
INFO: Initializing package repository C:\Users\dho\.julia\v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Conda from git://github.com/Luthaf/Conda.jl.git
INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of HttpCommon from git://github.com/JuliaWeb/HttpCommon.jl.g
it
INFO: Cloning cache of JSON from git://github.com/JuliaLang/JSON.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git

INFO: Installing BinDeps v0.3.15
INFO: Installing Compat v0.6.0
INFO: Installing Conda v0.1.1
INFO: Installing Dates v0.4.4
INFO: Installing HttpCommon v0.1.2
INFO: Installing JSON v0.4.5
INFO: Installing SHA v0.1.1
INFO: Installing URIParser v0.0.7
INFO: Building Conda
INFO: Precompiling module Compat...
INFO: Precompiling module URIParser...
INFO: Precompiling module SHA...
INFO: Downloading miniconda installer .
================================[ ERROR: Conda ]================================


LoadError: LoadError: InitError: could not spawn `'C:\Users\dho\.julia\v0.4\Cond
a\deps\usr\installer' -b -f -p 'C:\Users\dho\.julia\v0.4\Conda\deps\usr'`: no su
ch file or directory (ENOENT)
during initialization of module Conda
while loading C:\Users\dho\.julia\v0.4\Conda\src\Conda.jl, in expression startin
g on line 349
while loading C:\Users\dho\.julia\v0.4\Conda\deps\build.jl, in expression starti
ng on line 1

================================================================================


================================[ BUILD ERRORS ]================================


WARNING: Conda had build errors.

 - packages with build errors remain installed in C:\Users\dho\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("Conda")`
 - build a single package by running its `deps/build.jl` script

================================================================================

INFO: Package database updated

```
My version info is:
`
julia> versioninfo()
Julia Version 0.4.0-pre+7133
Commit 0f7dee9 (2015-09-01 22:04 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia>
```

**Comment by dhoegh** [comment]
It also errors on 0.3.

**Comment by Luthaf** [comment]
You just ran into that part of the README: 

> the code for Windows is present but untested.

I'll have to setup a virtual machine for Windows to fix that bug. 

To help me debugging, Is there any file at `C:\Users\dho\.julia\v0.4\Conda\deps\usr\installer` ?

**Comment by dhoegh** [comment]
Yes and it's size is approximately 36mb. But the file do not have any file extension. Maybe a problem on windows.

**Comment by dhoegh** [comment]
Thank you for your great work. I am looking forward for this work to on windows which would make Julia + IJulia + PyPlot easier to install in a corporate environment.

**Comment by Luthaf** [comment]
> But the file do not have any file extension. Maybe a problem on windows.

I think that is effectively (part of) the issue.

**Comment by Luthaf** [comment]
Testing of my fix is on it's way at https://ci.appveyor.com/project/Luthaf/conda-jl! I'll ask you to test in local when the Appveyor build will go green.

**Comment by Luthaf** [comment]
OK, it should be fixed now. Can you run the following to check if everything is allright?

```julia
Pkg.update()
Pkg.checkout("Conda", "windows")
Pkg.build("Conda")
Pkg.test("Conda")
# This line put back the Conda package to its previous state, so that Pkg.update() will update it.
Pkg.free("Conda")
```

**Comment by dhoegh** [comment]
I just gave it a run and it passes nicely, thank you so much. Tomorrow I will see if I can build my entire Julia setup(Jupyter + Matplotlib) with Conda.jl, if it succeed you made my promotion of Julia a bit easier:)

**Comment by dhoegh** [comment]
@Luthaf could you tag a new version of `Conda.jl` so these changes is included when you do `Pkg.add("Conda")`.

**Comment by Luthaf** [comment]
Done !

**Comment by dhoegh** [comment]
Thank you.
