### ISSUE TITLE
don't use Pkg.dir

### ISSUE THREAD

**Issue by stevengj** [Luthaf/Conda.jl#6]
You use `Pkg.dir("Conda", ...)` to find the package directory for the `PREFIX`.  This is wrong, because it breaks in cases where the package was cloned into some other location—see JuliaLang/julia#12120

The right thing to do is to use `dirname(@__FILE__)` to get the path of the current file.

**Comment by Luthaf** [comment]
Ok, I tought this was the official way. [Homebrew.jl](https://github.com/JuliaLang/Homebrew.jl/blob/afade35b9b54c5a9532f7dfc6d77b681437ad8fe/src/Homebrew.jl#L13) (my main inspiration here) does the same.
